### ISSUE TITLE
Stronger v7 > v6 > v1 preference claims

### ISSUE THREAD

**Issue by tgross35** [ietf-wg-uuidrev/rfc4122bis#126]
Would it make sense to be slightly more unambiguous that users should prefer v7, then v6, then v1 for time-based UUIDs?

In this document, v1 is referred to as "Gregorian time-based  UUID", v6 as "Reordered Gregorian time-based UUID", and v7 as "Unix Epoch time-based UUID". I am wondering if there may be value in renaming v1 and v6 to make it more clear that v6 is the preferred version of the two. For example, v1 could be referred to as "Compatible Gregorian time-based UUID" or "Legacy Gregorian..." and v6 as "Normalized Gregorian time-based UUID", or similar.

Otherwise, it seems that section `5.1. UUID Version 1` should contain language indicating that v7 is preferred where possible. Section `5.6.  UUID Version 6` states in the first paragraph `Systems that do not involve legacy UUIDv1 SHOULD use UUIDv7 instead.` - it seems like a similar statement would be suitable in section 5.1 as well.

(this may have been discussed elsewhere but I have not seen it)

**Comment by kyzer-davis** [comment]
Nobody has brought up the names as far as I can tell with no strong opposition as to what they are describes as in that version table. I would be hesitant to change those this late in the process. 

As for discouraging v1 in lieu of v7:
We could add some text like:
> It should be noted that this section is included for historical purposes. Implementations that require time-based UUIDs SHOULD use UUIDv7 {{UUIDv7_section_link}}.

**Comment by kyzer-davis** [comment]
Will let this one sit a bit to garner a few more thumbs up/down and/or discussion on the topic of marking "UUIDv1" legacy and pointing to v7. Again, somewhat late in the process so "big" changes like formally deprecating v1 within v1 section vs what is done in v6 section would need strong group feedback.

IMO the difference is that the text in v6 is saying "hey if you are implementing a new UUID type in 2023+ just do v7 vs bit swapping of v1" but saying "v1 is terrible use v7" could be a bridge too far. 

@bradleypeabody @LiosK whatcha think?

**Comment by danielmarschall** [comment]
I think that the new versions v6-v8 are great, but 
I am not sure if v7 could be described as a 100% successor of v1.

I think the **_direct_** successor of v1 is v6 because v6 has everything v1 has, just better (because it is ordered).

v7 has some differences which **_some_** people could argue as being disadvantages, making it not a 100% successor of v1:
1. The time resolution is not as good as in v1. When you create a lot of UUIDv7 and want that they are in the correct order, the code must sleep for 1 millisecond between UUIDv7 generations.
2. The MAC address - which some people or applications might consider useful metadata - is not available.
3. The random data could **_theoretically_** cause a collision, but very very very unlikely

I personally think that v6 and v7 are both equally good, and people could choose either v6 or v7, depending if they are okay with their MAC address included in the UUID or not.

**Comment by kyzer-davis** [comment]
I echo @danielmarschall's comment and advise to "leave it as is" with no text change to v1

**Comment by tgross35** [comment]
That comment makes sense, I did not consider the resolution / MAC components.

I do still think it may make sense to add something along the lines of `use cases that do not already employ v1 UUIDs will likely prefer  using v6 or v7 for improved ordering` - just to help answer the question of "when should I use this" early on. I think somebody may have brought this up on the list recently? However, I do understand that this may be considered too big a change at this point.

**Comment by LiosK** [comment]
My understanding is that v6 is introduced primarily for round-trip conversions from/to v1 and for ease of implementation utilizing the existing v1 generators. In this sense, v6 is like introduced for backward compatibility purposes, and thus it is natural to recommend v7 over v6 for other fresh-new use cases. Anyway, Sections 5.6 and 5.7 are clear enough that v7 is recommended over v6.

Now I was just wondering: should we recommend v6/v7 over v1? v1 and v6/v7 are both time-based but have different characteristics and use cases. v6/v7 isn't superior just because they are ordered. Some will choose v6/v7 if they need ordering while others might choose v1 otherwise. Now I don't really find a strong reason why we should discourage v1.

**Comment by kyzer-davis** [comment]
Going to close this one since the consensus seems to be that we do not need text changes in v1 section.
