### ISSUE TITLE
Hash Space IDs

### ISSUE THREAD

**Issue by danielmarschall** [ietf-wg-uuidrev/rfc4122bis#127]
The UUIDv8 contains custom, vendor-specific data and theoretically, the description of the contents would be out-of-scope for the RFC.

However, I agree that the sections "Example of a UUIDv8 Value (time-based)" and "Example of a UUIDv8 Value (name-based)" are good because they give people some inspiration about how a custom UUID could be designed.

But I am confused about the "Some Hash Space IDs" section because it is a main section, instead of a sub-section in the "Example of a UUIDv8" section. If I understand correctly, these Hash Space IDs are only used in this example, so I think they should be directly listed in the example.

What do you think?

**Comment by kyzer-davis** [comment]
I don't think it matters one way or the other by having them part of the test vector or as its own section. I just mimic'd what was done with name spaces and copy and pasted the section. I think I created the test vector later so that is probably why the hash space is after the name space section.

If anything I should probably just provide a reference in that test vector back to the hash space appendix.

I am trying to avoid changing too much here late in the state of IETF review and since it does not really help I will just add the missing appendix reference as the most minimal change.

**Comment by danielmarschall** [comment]
I hope you don't consider it as "spam", but I wanted to share that I have implemented the UUIDv8 namebased concept in my [open source solution](http://github.com/danielmarschall/uuid_mac_utils) and it can be tested here: https://misc.daniel-marschall.de/tools/uuid_mac_decoder/index.php#gen_uuidv35
... In case someone finds it useful (i.e. to generate or verify test vectors; I could reproduce that the SHA2-256 test vector `401835fd-a627-870a-873f-ed73f2bc5b2c` is correct.)

**Comment by kyzer-davis** [comment]
@danielmarschall, nope! I am a big advocate for real testing which provides valuable insight.
I have a prototype page here if you want to open a PR and cite the latest IETF draft for your v8 solution!
https://github.com/uuid6/prototypes
