### ISSUE TITLE
SECDIR Review

### ISSUE THREAD

**Issue by kyzer-davis** [ietf-wg-uuidrev/rfc4122bis#141]
```
Section 6.6
   High Impact:
      A duplicate key causes an airplane to receive the wrong course
      which puts people's lives at risk.  In this scenario there is no
      margin for error.  Collisions MUST be avoided and failure is
      unacceptable.  Applications dealing with this type of scenario
      MUST employ as much collision resistance as possible within the
      given application context.

Not to trivialize the seriousness of the described scenario, but normative
language around airplane design and operation doesn’t seem appropriate or in
scope for the WG.  Furthermore “as much collision resistance as possible” isn’t
particularly precise.  Recommend s/MUST/must/

** Section 6.9
   A generic approach, however, is
   to accumulate as many sources as possible into a buffer, use a
   message digest such as MD5 [RFC1321] or SHA-1 [FIPS180-4], take an
   arbitrary 6 bytes from the hash value, and set the multicast bit as
   described above.

RFC4112 referenced MD5 and SHA-1, but didn’t tie the implementation to them,
why can’t a modern hash algorithm (SHA-256) be recommended here instead?

** Section 6.11

   UUIDs SHOULD be treated as opaque values and implementations SHOULD
   NOT examine the bits in a UUID.  However, inspectors MAY refer to
   Section 4.1 and Section 4.2 when required to determine UUID version
   and variant.

   As general guidance, we recommend not parsing UUID values
   unnecessarily, and instead treating them as opaquely as possible.
   Although application-specific concerns could of course require some
   degree of introspection (e.g., to examine the variant, version or
   perhaps the timestamp of a UUID), the advice here is to avoid this or
   other parsing unless absolutely necessary.

Why are both of these paragraphs needed?  The first seems to say the same thing
as the second except with normative language.

** Section 8
Implementations SHOULD NOT assume that UUIDs are hard to guess. For example,
they MUST NOT be used as security capabilities (identifiers whose mere
possession grants access).

-- Why isn’t this a “MUST NOT assume”?

** Section 8
   MAC addresses pose inherent security risks and SHOULD NOT be used within a
   UUID.

Is there any advisory language that can be provided that could explain when a
MAC address should be used?
```

**Comment by kyzer-davis** [comment]
Will get to this in draft 12

**Comment by danielmarschall** [comment]
I have two thoughts/annotations:

(1)
I am confused about the definition "_Implementations SHOULD NOT assume that UUIDs are hard to guess_.".
Why is this so?  If I generate a UUIDv4 using a CSRNG and use it as BEARER in a REST-API, I basically have a 122-bit random number created using a CSRNG. This is very secure.
On the other hand, I know that not all UUID versions are that "secure". For example, a UUIDv2 is easy to guess and has a horrible time resolution.

In my opinion, since "some" UUID (e.g. UUIDv4 using CSRNG) are good as credentials, I think that it should stay "SHOULD NOT assume" and not "MUST NOT assume". I believe there are a lot of products that use UUIDv4 for tokens (e.g. Session Identifiers), and if you change the definition to "MUST NOT", it would mean that all these products must change their code.

---

(2) 
"_Is there any advisory language that can be provided that could explain when a MAC address should be used_?"
I cannot provide an advisory language, but I want to give a personal opinion and thoughts... Personally, I am an advocate for using real MAC in a UUID.
1. I see the MAC address as a kind of "signature". I can easily see if these UUIDs are created by myself or not. I think it is a nice touch when you develop Microsoft COM interfaces and all your UUIDs have the same ending. So people know "Hey, if the CLSID ends with 112233445566, this is a interface written by Contoso Ltd."
2. I can imagine that in a distributed computing environment, machines are generating data and identifying them with a UUID with a real MAC address. In case something is not good with the data, the machine producing the defective data can be identified. (I believe such "meta data" was extensively used in UUIDv2)
3. When choosing a random number as Node ID, the probability of a UUID collision is mathematically bigger than zero. If we use a real MAC address, the probability of collision is mathematically zero. I am stressing the word "mathematically" because I know that a collision is practically unlikely/impossible.

**Comment by kyzer-davis** [comment]
Changes from https://github.com/ietf-wg-uuidrev/rfc4122bis/commit/aa08603209711448575802658ffb828835199fb4
- Downgraded MUST to non-normative in high impact section
- Swapped MD5/SHA-1 for SHA-256 and SHA-512
- Removed extra paragraph in section 6.11, Opacity

Did not change language around section 8 (and the last item was already fixed in another issue tracker item.)
