### ISSUE TITLE
Revise 16-bit MAC Node Usage

### ISSUE THREAD

**Issue by tgross35** [ietf-wg-uuidrev/rfc4122bis#149]
> For systems with no IEEE address or utilizing an IEEE 802.15.4 16 bit address, a randomly or pseudo-randomly
generated value MUST be used; see {{unguessability}} and {{unidentifiable}}.
For systems utilizing a 64 bit MAC address the least significant, right-most 48 bits MAY be used.

Would it be better to say that 16-bit MACs and other MACs may use those 16 bits plus 32 random bits? Or otherwise weaken the `MUST`  such that shorter nonstandard MACs that still want a node identifier don't technically violate the spec.

**Comment by kyzer-davis** [comment]
Sure, you could include the 16-bit mac.
We would need to provide some guidance around where somebody would place the extra 32 bits of random.
E.g at the front  (Random+MAC) or at the end (MAC+Random) 
And with this in place does an implementation need to flip the MCAST bit?

**Comment by mcr** [comment]
So, 16-bit MACs are assigned centrally (00,01,02,) so that they are easily compressible.
Every 802.15.4 system that might use a 16-bit MAC also has a 64-bit MAC, which is "factory assigned", so for UUIDs they should always use that.

**Comment by tgross35** [comment]
Maybe that defeats the purpose then. "Must" just seemed a bit strong for devices that do have an identifier but not a 32-bit MAC

**Comment by kyzer-davis** [comment]
Would it be better to remove it from the first sentence and leave the MUST for those with no identifier and add a new line that states something like:
> Devices utilizing an IEEE 802.15.4 16 bit address SHOULD instead utilize their 64-bit MAC address where least significant, right-most 48 bits MAY be used. An alternative is to generate 32 bits of random data and postfix at the end of the 16 bit MAC address to create a 48 bit value.

**Comment by tgross35** [comment]
That sounds reasonable to me, as long as it doesn't throw a monkey wrench into the ongoing approval process

**Comment by kyzer-davis** [comment]
Modified in https://github.com/ietf-wg-uuidrev/rfc4122bis/commit/602dbacbff2789185b7b8d9c94cf0f96199217e7

**Comment by kyzer-davis** [comment]
For formatting/readability purposes via https://github.com/ietf-wg-uuidrev/rfc4122bis/commit/a749513acf572e91517cf17de12226334871aa2f:
- I removed this unneeded line: "The lowest addressed octet (octet number 10) contains the global/local bit and the unicast/multicast bit, and is the first octet of the address transmitted on an 802.3/802.11 LAN." 
- I moved the topic about selecting multiple addresses to the section grouping we have for no address, 16 bit and 64 bit. 
- I modified this to a list which I think reads a bit better. 
- I also cited 6.8/6.9 a bit earlier since it was only called out at the end of the v1 section.

Let me know what you all think.
